/* soapDocumentRightOperationsBindingService.h
   Generated by gSOAP 2.7.16 from IRM.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapDocumentRightOperationsBindingService_H
#define soapDocumentRightOperationsBindingService_H
#include "soapH.h"
class SOAP_CMAC DocumentRightOperationsBindingService : public soap
{ public:
	/// Constructor
	DocumentRightOperationsBindingService();
	/// Constructor with copy of another engine state
	DocumentRightOperationsBindingService(const struct soap&);
	/// Constructor with engine input+output mode control
	DocumentRightOperationsBindingService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	DocumentRightOperationsBindingService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~DocumentRightOperationsBindingService();
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Initializer used by constructor
	virtual	void DocumentRightOperationsBindingService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	DocumentRightOperationsBindingService *copy();
	/// Force close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	///

	/// Web service operation 'AssignRole' (returns error code or SOAP_OK)
	virtual	int AssignRole(_ns7__AssignRole *ns7__AssignRole, _ns7__AssignRoleResponse *ns7__AssignRoleResponse);

	/// Web service operation 'ReassignRole' (returns error code or SOAP_OK)
	virtual	int ReassignRole(_ns7__ReassignRole *ns7__ReassignRole, _ns7__ReassignRoleResponse *ns7__ReassignRoleResponse);

	/// Web service operation 'CheckInRightsForAccount' (returns error code or SOAP_OK)
	virtual	int CheckInRightsForAccount(_ns7__CheckInRightsForAccount *ns7__CheckInRightsForAccount, _ns7__CheckInRightsForAccountResponse *ns7__CheckInRightsForAccountResponse);

	/// Web service operation 'SaveChangesToItems' (returns error code or SOAP_OK)
	virtual	int SaveChangesToItems(_ns7__SaveChangesToItems *ns7__SaveChangesToItems, _ns7__SaveChangesToItemsResponse *ns7__SaveChangesToItemsResponse);

	/// Web service operation 'UnassignRights' (returns error code or SOAP_OK)
	virtual	int UnassignRights(_ns7__UnassignRights *ns7__UnassignRights, _ns7__UnassignRightsResponse *ns7__UnassignRightsResponse);

	/// Web service operation 'ListRightsByContext' (returns error code or SOAP_OK)
	virtual	int ListRightsByContext(_ns7__ListRightsByContext *ns7__ListRightsByContext, _ns7__ListRightsByContextResponse *ns7__ListRightsByContextResponse);

	/// Web service operation 'ListRightsByAccount' (returns error code or SOAP_OK)
	virtual	int ListRightsByAccount(_ns7__ListRightsByAccount *ns7__ListRightsByAccount, _ns7__ListRightsByAccountResponse *ns7__ListRightsByAccountResponse);
};
#endif
